### ISSUE TITLE
Inquiry Regarding [DRIPS: Dynamic Rebalancing of Pipelined Streaming Applications on CGRAs]

### ISSUE THREAD

**Issue by onzan-zyu** [tancheng/CGRA-Flow#27]
Hi tancheng,
   I am particularly interested in the application of Graph convolutional networks(GCNs) described in your paper. It may be a bit presumptuous, but I would like to have the source code of the example you choose. It would be of great help to me. I would greatly appreciate you guidance.

**Comment by tancheng** [comment]
Hi, thanks for your interest. Benchmark of GCN is [here](https://github.com/tancheng/Streaming-Bench/tree/main/gcn).

**Comment by onzan-zyu** [comment]
I am extremely grateful for your time and for addressing my questions. Your willingness to provide help is greatly appreciated. Thank you so much!!
